name: Docker build
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main